site_name: Streamlit-speech-to-text

repo_url: https://aaguayoo.github.io/streamlit-speech-to-text/tree/v0.1.0
repo_name: streamlit-speech-to-text@v0.1.0

nav:
   - Inicio: 'index.md'
   - Análisis de rendimiento: 'profiling_doc.md'
   - Documento de diseño: 'design_doc.md'
   - Ejemplos: 'examples.md'
   - API reference:
      - Model: 'api_reference/model.md'
      - Constants: 'api_reference/constants.md'
      - Decorators: 'api_reference/decorators.md'
      - Errors: 'api_reference/errors.md'
      - Schemas: 'api_reference/schemas.md'
      - Types: 'api_reference/types.md'
      - Warnings: 'api_reference/warnings.md'
      - Utils:
        - Utils: 'api_reference/utils/utils.md'

theme:
   name: 'material'
   logo: 'img/apervox.png'
   favicon: 'img/apervox.png'
   palette:
      - scheme: default
        toggle:
         icon: material/brightness-4
         name: Switch to dark mode
      - scheme: slate
        toggle:
         icon: material/brightness-7
         name: Switch to light mode

plugins:
   - search
   - autorefs
   - mkdocstrings
   - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
   version:
      provider: mike
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/LyticaMx

extra_css:
   - css/extra.css

markdown_extensions:
   - abbr
   - admonition
   - attr_list
   - def_list
   - footnotes
   - meta
   - toc:
       permalink: true
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem:
       smart_enable: all
   - pymdownx.caret
   - pymdownx.critic
   - pymdownx.details
   - pymdownx.highlight
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets:
       check_paths: true
   - pymdownx.superfences:
       custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed
   - pymdownx.tilde
   - pymdownx.tasklist:
        clickable_checkbox: true
        custom_checkbox: false

